version: '3'

services:
  vintrack:
    build: vintrack
    ports:
      - "8081:8080"
    environment:
      DB_URL: jdbc:mysql://vintrackbd:3306/vintrackbd?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      vintrackbd:
          condition: service_healthy
  vintrackbd:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: vintrackbd
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10